---
title: "writeup two"
author: "Tian Tan"
date: "March 31, 2016"
output: pdf_document
---


1.LR_interval
```{r}
Score_interval<-function(data,alpha){
  xbar=mean(data)
  n=length(data)
  z=qnorm((1+alpha)/2)
  output=list()
  output$lower=((2*xbar+z^2/n)-sqrt((2*xbar+z^2/n)^2-4*(xbar^2)))/2
  output$upper=((2*xbar+z^2/n)+sqrt((2*xbar+z^2/n)^2-4*(xbar^2)))/2
  return (output)
}


LR_interval<-function(data,alpha,tol=1e-9,max.iter=100){
  if (all(data==0)){
    cat("All the data values are zero\n")
    stop("function stops")
  }
  if (any(data%%1!=0)){
    cat("Some of the values are not integers\n")
  }
  if (any(data<0)){
    cat("There are negetive values\n")
    stop("function stops")
  }
  output=Score_interval(data,alpha)
  lower=output$lower
  upper=output$upper
  xbar=mean(data)
  z=qnorm((1+alpha)/2)
  n=length(data)
  fx_lower=-2*n*(xbar*log(lower/xbar)+xbar-lower)-z^2
  fx_upper=-2*n*(xbar*log(upper/xbar)+xbar-upper)-z^2
  i=0
  m=0
  k=0
  iter=0
  while((abs(fx_upper)>tol) && (abs(fx_lower)>tol) && (iter<max.iter)){
    dfx_lower=-2*n*(xbar/lower-1)
    dfx_upper=-2*n*(xbar/upper-1)
    lower=lower-fx_lower/dfx_lower
    upper=upper-fx_upper/dfx_upper
    iter=iter+1
    fx_lower=-2*n*(xbar*log(lower/xbar)+xbar-lower)-z^2
    fx_upper=-2*n*(xbar*log(upper/xbar)+xbar-upper)-z^2
  }
  return(list(lower = lower, upper = upper))
}

```

2. Tapply function
```{r}
horsekicks=read.csv("horsekicks.csv")
total_per_year=tapply(horsekicks$y,horsekicks$year,sum)
print(total_per_year)
```

3. 95% confidence interval for $\mu$
```{r}
data=matrix(total_per_year)
LR_interval(data[,1],alpha=0.95,tol=1e-9,max.iter=100)
```

4. Exact interval
```{r}
FindDeriv<-function(ftn, x){
  fx=ftn(x)
  epsilon=(10^-7)*x
  epsilon2=(10^-7)*(x+24*epsilon)
  if (x==0){
    epsilon=10^-6
    epsilon2=10^-6*(1+24*epsilon)
  }
  dfx=(ftn(x+epsilon)-ftn(x))/epsilon
  ddfx=((ftn(x+epsilon+epsilon2)-ftn(x+epsilon))/epsilon2-dfx)/epsilon
  return(c(fx,dfx,ddfx))
}

newtonraphson2<-function(ftn, x0, tol = 1e-9, max.iter = 100){
  x=x0
  fx=FindDeriv(ftn,x)
  iter=0
  eplison=10^-6/x
  while ((abs(fx[1]) > tol) && (iter < max.iter)) {
    x=x - fx[1]/fx[2]
    fx=FindDeriv(ftn,x)
    iter=iter+1
  }
  if (abs(fx[1]) > tol) {
    cat("Algorithm failed to converge\n")
    return(NULL)
  } else {
    return(c(x,iter))
  }
}


Exact_interval<-function(data,alpha,tol=1e-9,max.iter=100){
  possionupper<-function(nmu,value=data,ALPHA=alpha){
    X=sum(value)
    return(ppois(X,nmu)-0.5*dpois(X,nmu)-ALPHA/2)
  }
  possionlower<-function(nmu,value=data,ALPHA=alpha){
    X=sum(value)
    return(1-ppois(X,nmu)+0.5*dpois(X,nmu)-ALPHA/2)
  }
  n=length(data)
  X=sum(data)
  lower_output=newtonraphson2(possionlower,X)
  upper_output=newtonraphson2(possionupper,X)
  lower=lower_output[1]/n
  upper=upper_output[1]/n
  return(list(lower = lower, upper = upper))
}

```

5. Tabulate the LR, Score and Exact confidence intervals
```{r}
Score=Score_interval(data[,1],0.95)
LR=LR_interval(data[,1],alpha=0.95,tol=1e-9,max.iter=100)
Exact=Exact_interval(data[,1],alpha=0.05,tol=1e-9,max.iter=100)
rbind(Score,LR,Exact)
```

cite: work with Rui Chen

